<a href="https://colab.research.google.com/github/mariamg841/Mental-Health-Thesis/blob/main/Thesis_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as no 
import matplotlib.pyplot as plt 
import seaborn as sns

%matplotlib inline 
plt.style.use("seaborn")
df = pd.read_csv('https://raw.githubusercontent.com/mariamg841/Mental-Health-Thesis/main/Untitled%20form%20(Responses)%20-%20Form%20responses%201.csv')
df.head()

<ipython-input-13-524f5d29259a>:7: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use("seaborn")


Timestamp  Age:   Gender  \
0  30/04/2023 15:31:44  21-30  Female   
1  30/04/2023 15:36:10  21-30    Male   
2  30/04/2023 15:38:41  21-30  Female   
3  30/04/2023 15:38:47  15-20    Male   
4  30/04/2023 15:39:09  15-20    Male   

   Overall how would you rate your physical health?  \
0                                                 4   
1                                                 2   
2                                                 3   
3                                                 4   
4                                                 3   

   Overall how would you rate your mental health?  \
0                                               3   
1                                               2   
2                                               3   
3                                               2   
4                                               4   

  During the past 4 weeks, have you had any problems with your work or daily life due to your physical health?  \
0                                                 No                                                             
1                                              Maybe                                                             
2                                                Yes                                                             
3                                              Maybe                                                             
4                                                Yes                                                             

  During the past 4 weeks, have you had any problems with your work or daily life due to any emotional problems, such as feeling depressed, sad or anxious?  \
0                                              Maybe                                                                                                          
1                                                Yes                                                                                                          
2                                                Yes                                                                                                          
3                                                Yes                                                                                                          
4                                                 No                                                                                                          

  Do you consider yourself as a person who suffers from a mental illness?  \
0                                              Maybe                        
1                                              Maybe                        
2                                              Maybe                        
3                                                 No                        
4                                              Maybe                        

  Do you or any of your family members have history of a mental illness?  \
0                                                 No                       
1                                                Yes                       
2                                                 No                       
3                                                 No                       
4                                                Yes                       

  Do you consider yourself as a person who accepts  Psychotherapy؟  ...  \
0                                                Yes                ...   
1                                                Yes                ...   
2                                                Yes                ...   
3                                                 No                ...   
4                                                 No                ...   

  Have you noticed any change in your diet habits?  \
0                                        No Change 

In [14]:
df.rename(columns = {'Overall how would you rate your physical health?':'PH rate','Overall how would you rate your mental health?':'MH rate','During the past 4 weeks, have you had any problems with your work or daily life due to your physical health?':'physical health effect','During the past 4 weeks, have you had any problems with your work or daily life due to any emotional problems, such as feeling depressed, sad or anxious?':'MH effect', 'Do you consider yourself as a person who suffers from a mental illness?':'has a mental illness', 'Do you or any of your family members have history of a mental illness?':'history of mental illness','Do you consider yourself as a person who accepts  Psychotherapy؟':'Accepts  Psychotherapy', 'Have you changed your routine recently?':'Routine', 'Are you going through a tough emotional situation?': 'Tough ES', 'How often do you smoke?':'Smoke', 'How is your quality of sleep?':'Quality Of Sleep','How many hours do you sleep per day?':'Sleep Hrs', 'Do you consider yourself as a person who sees things': 'Perspective', 'Have you noticed any change in your diet habits?':'Diet Habits','Have you changed your routine recently?':'Routine', 'Are you going through a tough emotional situation?': 'Tough ES', 'How often do you smoke?':'Smoke', 'How is your quality of sleep?':'Quality Of Sleep','How many hours do you sleep per day?':'Sleep Hrs', 'Do you consider yourself as a person who sees things': 'Perspective', 'Have you noticed any change in your diet habits?':'Diet Habits', 'How often do you experience below? [Angry]':'Angry', 'How often do you experience below? [Gloomy]': 'Gloomy', 'How often do you experience below? [Energetic]': 'Energetic', 'How often do you experience below? [Calm and peaceful]': 'Calm and peaceful', 'Do you feel content with your relationships and family?': 'Content', 'What is your relationship status?': 'Relationship', 'During the past two weeks, how often has your mental health affected your relationships?' : 'Relationship Affected by MH','Have you changed your routine recently?' : 'Routine', 'Are you going through a tough emotional situation?' : 'Tough ES', 'How often do you smoke?' : 'Smoke', 'How is your quality of sleep?' : 'Quality Of Sleep', 'How many hours do you sleep per day?' : 'Sleep Hrs', 'Do you consider yourself as a person who sees things' : 'Perspective', 'Have you noticed any change in your diet habits?' : 'Diet Habits', 'How often do you experience below? [Angry]' : 'Angry', 'How often do you experience below? [Gloomy]' : 'Gloomy', 'How often do you experience below? [Energetic]' : 'Energetic', 'How often do you experience below? [Calm and peaceful]' : 'Calm and peaceful', 'Do you feel content with your relationships and family?' : 'Content', 'What is your relationship status?' : 'Relationship', 'During the past two weeks, how often has your mental health affected your relationships?' : 'Relationship Affected by MH' , 'How often do you feel particularly low or down for more than 2 weeks in a row?' : 'Feel Down' , 'Are you currently taking any medication?' : 'Medication' , 'Have you been diagnosed with any of the following illnesses?' : 'Illness' , 'How often do you visit a psychiatric?' :'Psychiatric' , 'Age: ' : 'Age' }, inplace=True)

df

Timestamp    Age  Gender  PH rate  MH rate  \
0    30/04/2023 15:31:44  21-30  Female        4        3   
1    30/04/2023 15:36:10  21-30    Male        2        2   
2    30/04/2023 15:38:41  21-30  Female        3        3   
3    30/04/2023 15:38:47  15-20    Male        4        2   
4    30/04/2023 15:39:09  15-20    Male        3        4   
..                   ...    ...     ...      ...      ...   
119  08/05/2023 10:01:33    40+    Male        3        4   
120  08/05/2023 11:49:24    40+    Male        3        4   
121  08/05/2023 11:57:43    40+    Male        4        4   
122  08/05/2023 12:00:10    40+    Male        3        3   
123  08/05/2023 19:56:41  21-30    Male        3        3   

    physical health effect MH effect has a mental illness  \
0                       No     Maybe                Maybe   
1                    Maybe       Yes                Maybe   
2                      Yes       Yes                Maybe   
3                    Maybe       Yes                   No   
4                      Yes        No                Maybe   
..                     ...       ...                  ...   
119                     No        No                   No   
120                     No       Yes                   No   
121                     No       Yes                   No   
122                     No       Yes                   No   
123                     No       Yes                   No   

    history of mental illness Accepts  Psychotherapy  ...  \
0                          No                    Yes  ...   
1                         Yes                    Yes  ...   
2                          No                    Yes  ...   
3                          No                     No  ...   
4                         Yes                     No  ...   
..                        ...                    ...  ...   
119                        No                    Yes  ...   
120                        No                    Yes  ...   
121                        No                     No  ...   
122                        No                    Yes  ...   
123                       Yes                    Yes  ...   

                  Diet Habits                  Perspective Sleep Hrs  \
0                   No Change  from a positive perspective        9+   
1    Yes, I don't feel hungry                  As they are       7-9   
2    Yes, I don't feel hungry  from a negative perspective       7-9   
3                   No Change                  As they are       7-9   
4    Yes, I don't feel hungry                  As they are       7-9   
..                        ...                          ...       ...   
119       Yes, I eat too much  from a positive perspective       7-9   
120                 No Change                  As they are       7-9   
121                 No Change  from a positive perspective       7-9   
122                 No Change                  As they are        9+   
123  Yes, I don't feel hungry  from a positive perspective       7-9   

    Quality Of Sleep                    Smoke Tough ES           Routine  \
0                  4         Once a few weeks       No     Yes, slightly   
1                  3                    Never      Yes  Yes, quite a bit   
2                  3         Once a few weeks      Yes                No   
3                  1                    Never       No                No   
4                  2                    Never       No  Yes, quite a bit   
..               ...                      ...      ...               ...   
119                4           Once every day       No     Yes, slightly   
120                4  More than once everyday      Yes                No   
121                3                    Never       No                No   
122                4           Once every day       No     Yes, slightly   
123                4         Once a few weeks       No  Yes, quite a bit   

    Do you consider mental health as a

In [15]:
df = df.drop("Do you want to share any comments?", axis='columns')
df = df.drop("How much would you like the idea of an application on smartphones that can track your mental health state?", axis='columns')
df = df.drop("Do you consider mental health as an important topic that needs more attention?", axis='columns')
df = df.drop("Timestamp", axis='columns')
df

Age  Gender  PH rate  MH rate physical health effect MH effect  \
0    21-30  Female        4        3                     No     Maybe   
1    21-30    Male        2        2                  Maybe       Yes   
2    21-30  Female        3        3                    Yes       Yes   
3    15-20    Male        4        2                  Maybe       Yes   
4    15-20    Male        3        4                    Yes        No   
..     ...     ...      ...      ...                    ...       ...   
119    40+    Male        3        4                     No        No   
120    40+    Male        3        4                     No       Yes   
121    40+    Male        4        4                     No       Yes   
122    40+    Male        3        3                     No       Yes   
123  21-30    Male        3        3                     No       Yes   

    has a mental illness history of mental illness Accepts  Psychotherapy  \
0                  Maybe                        No                    Yes   
1                  Maybe                       Yes                    Yes   
2                  Maybe                        No                    Yes   
3                     No                        No                     No   
4                  Maybe                       Yes                     No   
..                   ...                       ...                    ...   
119                   No                        No                    Yes   
120                   No                        No                    Yes   
121                   No                        No                     No   
122                   No                        No                    Yes   
123                   No                       Yes                    Yes   

    Psychiatric  ...         Energetic            Gloomy             Angry  \
0         Never  ...  Most of the time   Once in a while             Never   
1         Never  ...  Most of the time   Once in a while             Never   
2         Never  ...  Most of the time   Once in a while   Once in a while   
3         Never  ...   Once in a while             Never             Never   
4         Never  ...            Always   Once in a while  Most of the time   
..          ...  ...               ...               ...               ...   
119       Never  ...   Once in a while   Once in a while   Once in a while   
120        Once  ...  Most of the time   Once in a while   Once in a while   
121       Never  ...  Most of the time   Once in a while   Once in a while   
122       Never  ...   Once in a while  Most of the time   Once in a while   
123       Never  ...  Most of the time  Most of the time  Most of the time   

                  Diet Habits                  Perspective Sleep Hrs  \
0                   No Change  from a positive perspective        9+   
1    Yes, I don't feel hungry                  As they are       7-9   
2    Yes, I don't feel hungry  from a negative perspective       7-9   
3                   No Change                  As they are       7-9   
4    Yes, I don't feel hungry                  As they are       7-9   
..                        ...                          ...       ...   
119       Yes, I eat too much  from a positive perspective       7-9   
120                 No Change                  As they are       7-9   
121                 No Change  from a positive perspective       7-9   
122                 No Change                  As they are        9+   
123  Yes, I don't feel hungry  from a positive perspective       7-9   

    Quality Of Sleep                    Smoke Tough ES           Routine  
0                  4         Once a few weeks       No     Yes, slightly  
1                  3                    Never      Yes  Yes, quite a bit  
2                  3         Once a few weeks      Yes                No  
3                  1                    Never       No                No  
4                  2        

In [16]:
df['Age'] = pd.Categorical(df['Age'], 
                                      categories=['15-20', '21-30', '31-40', '40+'], 
                                      ordered=True)
df['Psychiatric'] = pd.Categorical(df['Psychiatric'], 
                                      categories=['Regularly', 'Every once in a while', 'Once', 'Never'], 
                                  ordered=True)

In [17]:
#Label encoding
df_encoded = df.copy()
df_encoded['Age'] = df_encoded['Age'].cat.codes
df_encoded['Psychiatric'] = df_encoded['Psychiatric'].cat.codes

df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Age                          124 non-null    int8  
 1   Gender                       124 non-null    object
 2   PH rate                      124 non-null    int64 
 3   MH rate                      124 non-null    int64 
 4   physical health effect       124 non-null    object
 5   MH effect                    124 non-null    object
 6   has a mental illness         124 non-null    object
 7   history of mental illness    124 non-null    object
 8   Accepts  Psychotherapy       124 non-null    object
 9   Psychiatric                  124 non-null    int8  
 10  Illness                      73 non-null     object
 11  Medication                   124 non-null    object
 12  Feel Down                    124 non-null    object
 13  Relationship Affected by MH  124 no

In [18]:
df['MH effect']= pd.Categorical(df['MH effect'],
                           categories=['Yes', 'No', 'Maybe'],
                           ordered=True)

df['MH effect'] = df['MH effect'].astype('category').cat.codes
categorical_columns = df.select_dtypes(include= [object, 'category']).columns
df_encoded = pd.get_dummies(data=df,
                           columns=categorical_columns,
                           dtype='int8')
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Columns: 118 entries, PH rate to Routine_Yes, slightly
dtypes: int64(3), int8(115)
memory usage: 17.0 KB


In [19]:
from sklearn.model_selection import train_test_split

X_ohe = df_encoded.drop('MH effect', axis=1)
y_ohe = df_encoded['MH effect']

X_train_ohe, X_test_ohe, y_train_ohe, y_test_ohe = train_test_split(X_ohe, y_ohe, test_size=0.3, random_state=42)

In [20]:
from sklearn.ensemble import RandomForestClassifier
random_forest_clf_ohe = RandomForestClassifier(random_state=42) 
random_forest_clf_ohe.fit(X_train_ohe,y_train_ohe)

RandomForestClassifier(random_state=42)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
print_score(random_forest_clf_ohe, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe, train=True)
print_score(random_forest_clf_ohe, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe,train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0     1     2  accuracy  macro avg  weighted avg
precision   1.0   1.0   1.0       1.0        1.0           1.0
recall      1.0   1.0   1.0       1.0        1.0           1.0
f1-score    1.0   1.0   1.0       1.0        1.0           1.0
support    53.0  16.0  17.0       1.0       86.0          86.0
_______________________________________________
Confusion Matrix: 
 [[53  0  0]
 [ 0 16  0]
 [ 0  0 17]]

Test Result:
Accuracy Score: 65.79%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1         2  accuracy  macro avg  weighted avg
precision   0.666667   0.750000  0.500000  0.657895   0.638889      0.664474
recall      0.952381   0.272727  0.333333  0.657895   0.519481      0.657895
f1-score    0.784314   0.400000  0.400000  0.657895   0.528105      0.612384
support    21.000000  11.000000  6.000000  0.657895  38

In [22]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train_ohe, y_train_ohe)

#Predict the response for test dataset
y_pred = clf.predict(X_test_ohe)

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
print_score(clf, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe, train=True)
print_score(clf, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe,train=False)

Train Result:
Accuracy Score: 100.00%
_________________
CLASSIFICATION REPORT:
              0     1     2  accuracy  macro avg  weighted avg
precision   1.0   1.0   1.0       1.0        1.0           1.0
recall      1.0   1.0   1.0       1.0        1.0           1.0
f1-score    1.0   1.0   1.0       1.0        1.0           1.0
support    53.0  16.0  17.0       1.0       86.0          86.0
_________________
Confusion Matrix: 
 [[53  0  0]
 [ 0 16  0]
 [ 0  0 17]]

Test Result:
Accuracy Score: 57.89%
_________________
CLASSIFICATION REPORT:
                   0          1         2  accuracy  macro avg  weighted avg
precision   0.666667   0.400000  0.500000  0.578947   0.522222      0.563158
recall      0.761905   0.363636  0.333333  0.578947   0.486291      0.578947
f1-score    0.711111   0.380952  0.400000  0.578947   0.497354      0.566416
support    21.000000  11.000000  6.000000  0.578947  38.000000     38.000000
_________________
Confusion Matrix: 
 [[16  4  1]
 [ 6  4  1]
 [ 2  

In [24]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train_ohe,y_train_ohe)

DecisionTreeClassifier(random_state=42)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
print_score(tree_clf, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe, train=True)
print_score(tree_clf, X_train_ohe, y_train_ohe, X_test_ohe, y_test_ohe,train=False)

Train Result:
Accuracy Score: 100.00%
_________________
CLASSIFICATION REPORT:
              0     1     2  accuracy  macro avg  weighted avg
precision   1.0   1.0   1.0       1.0        1.0           1.0
recall      1.0   1.0   1.0       1.0        1.0           1.0
f1-score    1.0   1.0   1.0       1.0        1.0           1.0
support    53.0  16.0  17.0       1.0       86.0          86.0
_________________
Confusion Matrix: 
 [[53  0  0]
 [ 0 16  0]
 [ 0  0 17]]

Test Result:
Accuracy Score: 52.63%
_________________
CLASSIFICATION REPORT:
                   0          1         2  accuracy  macro avg  weighted avg
precision   0.750000   0.750000  0.142857  0.526316   0.547619      0.654135
recall      0.714286   0.272727  0.333333  0.526316   0.440115      0.526316
f1-score    0.731707   0.400000  0.200000  0.526316   0.443902      0.551733
support    21.000000  11.000000  6.000000  0.526316  38.000000     38.000000
_________________
Confusion Matrix: 
 [[15  1  5]
 [ 1  3  7]
 [ 4  